### ISSUE TITLE
Create F2F agenda - 16 September 2019

### ISSUE THREAD

**Issue by mfalken** [w3c/ServiceWorker#1460]
# Where

**Location:** [TPAC](https://www.w3.org/2019/09/TPAC/), Fukuoka, Japan
**When:** 9 AM, 16 September 2019
**IRC:** #serviceworker on irc.w3.org.

# Shared doc

* https://docs.google.com/document/d/1q090ovJ4gd8wSfVtvuoZLMZ51YkiFDsEZ0Jiqi41Iys/edit?usp=sharing

# Attendance

Please register at the [TPAC registration page](https://www.w3.org/2019/09/TPAC/registration.html). Members can access the [registration list](https://www.w3.org/register/tpac2019/registrants).

# Agenda

## HELLO EVERYONE

Find out who everyone is and why.

## Implementer update

Share implementation recent progress, priorities, plans, problems, etc.

## CFAM (that's "Call for agenda modification". I'm making it a thing – Jake)

* Anything folks want to cover that isn't part of the agenda?
* Any items that should be done at a certain time, or depend on particular people?

## Interesting new feature requests

* [x] Support efficient offline redirects: #1457 - Need Anne
* [ ] A way to specify a pattern of destination URLs to hit/skip SW #1454 - Need N8, Anne
  * [ ] Related #1195, #1026 
* [x] Scope Pattern Matching #1468 - Need Anne
* [x] DONE Client lifecycle with bfcache, frozen tabs
  * [x] Add an option to include frozen documents. #1442
  * [x] Consider how Client API should behave with bfcache: #1038.
  * [x] Related #626
* [x] bg fetch & bg sync privacy stuff
* [x] (Heads up): Periodic Background Sync https://github.com/beverloo/periodic-background-sync
* [x] (Heads up): Content Index https://github.com/rknoll/content-index
* [x] (Heads up): Launch event https://github.com/WICG/sw-launch/blob/master/explainer.md
* [x] (Update): Declarative routes https://github.com/w3c/ServiceWorker/issues/1373#issuecomment-452247362
  * [ ] Needs implementer interest
  * [ ] What next? Would a polyfill or spec help?
* [x] SW lifetime:
  * [x] A way to immediately unregister a service worker #614
  * [ ] Allow active worker to immediately evict itself #1296 
  * [x] Clear-Site-Data problems?
* [ ] Spec/design notes for double-keyed service workers
  * [ ] What do browsers do/plan to do
  * [ ] Should there be spec changes and how. Tests?
  * [ ] https://github.com/whatwg/html/issues/3338 is the only thing I can find. So it feels too early for us to do anything – Jake
* [ ] Top-level await integration for ServiceWorkers running modules #1407
* [x] Fetch streaming upload: https://github.com/whatwg/fetch/pull/425
  * [ ] New interest from Chrome
  * [ ] But not bi-directional (getting response object will be gated on request end)
  * [ ] Is that a step in the right direction? If we do the full thing later, it's kinda difficult to feature detect.
* [x] Registering service workers for unique origins? #1437 
* [x] provide a way to execute work after browser has consumed a response #1397
* [ ] Linking data to a service worker #1387
* [ ] Expose `display` mode (e.g. `standalone`) on `client` #1370
* [ ] Replay POST requests (add request to IDB) https://github.com/w3c/ServiceWorker/issues/693
* [ ] Do we want to do something about the single tab 'refresh' case? https://github.com/w3c/ServiceWorker/issues/1238

## V1 & W3C living spec

* [x] Double check everyone is happy with v1 going to CR.
  * [x] Do we stop updating v1 now?
* [x] Rechartering, and which specs we bring in.
  * [ ] Background sync (including periodic).
  * [ ] Background fetch.
  * [ ] Where should cache go?
* [x] How will "living standard" work going forward, and are we happy with it?

Plh will be around 14:30 to chat about this.

## Changes & bugs

Feel free to add to this list.

* [ ] "no-cors" CSS SOP violation #719 
* [ ] spec says cache should return responses with immutable headers, but no browser does that #1456 
* [ ] Add registeringClientId to the ServiceWorker object #1379
* [ ] Clarification on what happens during a terminated activation #1372 
* [ ] Update order of service worker properties https://github.com/w3c/ServiceWorker/issues/1273#issuecomment-502135609
* [ ] Should the order of registrations returned by getRegistrations() be sorted by scope? #1465
* [ ] Issue with progress and uploads https://github.com/w3c/ServiceWorker/issues/1141
* [ ] Status update for https://github.com/w3c/ServiceWorker/issues/1013
* [ ] Set request origin in update https://github.com/w3c/ServiceWorker/issues/1447
* [ ] Calling update when there's an installing worker https://github.com/w3c/ServiceWorker/issues/1429

## Dinner

Unfortunately, dinner registration is closed. If you registered (see below list), here are the details:

* Location: Yohira (https://goo.gl/maps/aNyJhFui45FJVKBj6)
* Time: 7pm
* Registered people: acomminos, asa.kusuma, asuth, bashi, beverloo, dharani, dom, domenic, dpc, falken, hayato, jakearchibald, jungkee.song, mek, n8s, nhiroki, rayankanso, shimazu, (slightlyoff), stevebe, tsteiner, wanderview, yhirano, youenn, yutakasai

It's a 30-45 min walk (3 km) from the hotel or 10 minute taxi. Meet at 6:30 at the hotel front lobby (4F) if you want to taxi over.

**Comment by wanderview** [comment]
I'm working on a proposal giving sites more control over how scopes match that I'd like to discuss.  I'm hoping to post as an issue later this week or early next week.

**Comment by asakusuma** [comment]
Thanks for putting this together @mattto. Regarding the `SW Lifetime` item, another possible sub-item would be the "abortable algorithms" proposal https://github.com/w3c/ServiceWorker/pull/1443 (cc @jakearchibald). That proposal may be part of the puzzle to landing an algorithm for killing a service worker https://github.com/w3c/ServiceWorker/pull/1440, which would also be a good sub-item for the `SW Lifetime` discussion.

**Comment by mattto** [comment]
Thanks, @wanderview and @asakusuma. Incorporated into the issue.

**Comment by mattto** [comment]
Would people be interested in a group dinner after the meeting? If you're interested in joining, can you thumbs up this?

**Comment by wanderview** [comment]
FYI, I've filed #1468 with my service worker scope proposal.

**Comment by mattto** [comment]
I made a dinner reservation at a nearby place for after the meeting. It will be a course meal of recommended seasonal food (kaiseki). If you want to attend, please fill out this form by **Thursday, Sept 12** at 5pm (in your timezone): https://forms.gle/wcGRxDtsBwQokRRS9

I'll have to confirm the number of people by then. Thanks!

**Comment by mattto** [comment]
Final reminder for dinner: If you want to attend, please fill out the form asap!

The following people are registered: acomminos, asa.kusuma, asuth, bashi, dharani, (domenic), falken, hayato, jakearchibald, mek, n8s, shimazu, slightlyoff, tsteiner, wanderview, yutakasai

**Comment by yutakahirano** [comment]
Can we talk about fetch streaming upload (https://github.com/whatwg/fetch/pull/425)?

**Comment by jakearchibald** [comment]
Note we're now starting at 9am rather than 8:30am, because we're not monsters.
